### ISSUE TITLE
Firefox で 縮小して全体を表示 相当処理が動かない

### ISSUE THREAD

**Issue by cat-in-136** [ttskch/svg-paper-example#1]
Firefox で 縮小して全体を表示 相当処理が動かないため、文字が重なって表示されることがあります。
確認環境: Firefox 89/90b3
![Screenshot見積書（金額あり）](https://user-images.githubusercontent.com/379009/120910412-cae22600-c6b9-11eb-964e-b1357bf30724.png)

これは下記のサイトに書かれているとおり Firefox の未実装・バグに起因する互換性問題です（実際には Firefox を非対応として問題を閉じるのも現実的な手でしょう）。

https://stackoverflow.com/questions/13122790/how-to-get-svg-element-dimensions-in-firefox
https://bugzilla.mozilla.org/show_bug.cgi?id=890692

対処するには、未実装機能を避けた実装する必要があります。たとえば下記のようなコードを読み込み後デバッグコンソールにコピペすることで、商品名欄について **縮小して全体表示** が表示されるようになります。

```javascript
{
  const boundingClientRectZoom = document.querySelector('#見積書_金額あり_ rect[width="2100"]')
    .getBoundingClientRect().width / 2100;
  const config = { textLength: 665 };
  for (const e of document.querySelectorAll('[id^="_商品名_"]')) {
    const w = e.getBoundingClientRect().width;
    if (w > config.textLength * boundingClientRectZoom) {
      e.setAttribute('textLength', config.textLength)
      e.setAttribute('lengthAdjust', 'spacingAndGlyphs')
    }
  }
}
```

**Comment by ttskch** [comment]
@cat-in-136 報告ありがとうございました！修正しました！

> clientWidthが取得できていなかったのは [インライン要素に対しては0になるという仕様](https://developer.mozilla.org/ja/docs/Web/API/Element/clientWidth#:~:text=%E3%82%A4%E3%83%B3%E3%83%A9%E3%82%A4%E3%83%B3%E8%A6%81%E7%B4%A0%E3%82%84%20css%20%E3%81%AE%E3%81%AA%E3%81%84%E8%A6%81%E7%B4%A0%E3%81%A6%E3%82%99%E3%81%AF%E3%82%BB%E3%82%99%E3%83%AD%E3%81%AB%E3%81%AA%E3%82%8A%E3%81%BE%E3%81%99%E3%80%82) によるものだったようです
